"use client";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "@/components/CartContext";
import "./globals.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey="pk_test_c3BsZW5kaWQtY2FtZWwtMTguY2xlcmsuYWNjb3VudHMuZGV2JA">
      <CartProvider>
        <html lang="en">
          <head>
            <title>E-commerce website</title>
            <meta
              name="description"
              content="Generated by create next app"
            />
          </head>
          <body>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
